# QWall2 AI 地图导航系统配置

# 服务器配置
server:
  port: 8090
  host: "0.0.0.0"

# AI 配置
ai:
  default_provider: "chatgpt"  # mock, claude, chatgpt, deepseek
  
  # Claude AI (推荐)
  claude:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "${ANTHROPIC_MODEL:-claude-3-5-sonnet-20241022}"
    base_url: "${ANTHROPIC_BASE_URL:-https://api.anthropic.com/v1}"
  
  # ChatGPT (需要 OpenAI API Key)
  chatgpt:
    api_key: "sk-42ff57db37985902f95302c75425d8bc80208ba44cc18ffeb78fd7feea662f88"
    model: "${OPENAI_MODEL:-claude-4.5-sonnet}"
    base_url: "${OPENAI_BASE_URL:-https://openai.qiniu.com/v1}"
  
  # DeepSeek (需要 DeepSeek API Key)
  deepseek:
    api_key: "${DEEPSEEK_API_KEY}"
    model: "${DEEPSEEK_MODEL:-deepseek-chat}"
    base_url: "${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}"

# 地图配置
map:
  default_provider: "baidu"  # baidu, amap, google

# STT 配置 (语音识别 - 可选)
stt:
  provider: "auto"  # auto, openai, local, aliyun
  openai_key: "${OPENAI_API_KEY}"
  model: "${WHISPER_MODEL:-whisper-1}"
  aliyun_api_key: "${ALIYUN_API_KEY}"
  aliyun_model: "${ALIYUN_MODEL:-paraformer-realtime-v2}"
  enable_fallback: true
  local_model_path: "/usr/local/share/whisper/models"