server:
  port: 8090
  host: "0.0.0.0"

# STT 配置
stt:
  provider: "auto"              # auto, openai, local, aliyun
  openai_key: "${OPENAI_API_KEY}"
  model: "${WHISPER_MODEL:-whisper-1}"  # 支持环境变量，默认 whisper-1
  aliyun_api_key: "${ALIYUN_API_KEY}"   # 阿里云 API Key
  aliyun_model: "${ALIYUN_MODEL:-paraformer-realtime-v2}"  # 阿里云模型
  enable_fallback: true         # 启用降级
  local_model_path: "/usr/local/share/whisper/models"

# AI 配置
ai:
  default_provider: "chatgpt"   # chatgpt, claude, deepseek
  
  chatgpt:
    api_key: "${OPENAI_API_KEY}"
    model: "${OPENAI_MODEL:-gpt-3.5-turbo}"  # 支持环境变量，默认 gpt-3.5-turbo
    base_url: "${OPENAI_BASE_URL:-https://api.openai.com/v1}"  # 支持环境变量
  
  claude:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "${ANTHROPIC_MODEL:-claude-3-5-sonnet-20241022}"  # 支持环境变量
    base_url: "${ANTHROPIC_BASE_URL:-https://api.anthropic.com/v1}"  # 支持环境变量
  
  deepseek:
    api_key: "${DEEPSEEK_API_KEY}"
    model: "${DEEPSEEK_MODEL:-deepseek-chat}"  # 支持环境变量
    base_url: "${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}"  # 支持环境变量

# 地图配置
map:
  default_provider: "baidu"     # baidu, amap, google
